version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=esit

  adminer:
    image: adminer
    ports:
      - "9998:8080"
    links:
      - db
